apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec: # pvc의 정보를 입력하는 파트
  accessModes:
    - ReadWriteMany # ReadWriteOnce, ReadWriteMany 옵션을 선택할 수 있음
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi # storage 용량 설정
  storageClassName: standard # `kubectl get storageclass`를 통해 확인한 storageclass의 name 입력